name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install || echo "No package.json found"

      - name: Build Application
        run: npm run build || echo "No build step"


  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run Tests
        run: npm test || echo "No tests available"


  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Deploy Application
        run: echo "Application deployed successfully"
